### ISSUE TITLE
Data Processing / Bulk Image Export - Export Reference Images

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#78] opened 2020-02-26 09:09 UTC
An tool needs to be created within IDS that allows users to export only images tagged as reference images (in order to prep for reco). I suggest that this be added into the Data Processing/Bulk Image Export module, as an additional section located under the Export by Individual section.

**Comment by PhilipFaure** [comment] 2020-03-17 17:54
Closing Issue. Checkbox button added to allow user to export reference images only into individual folders in a specified location.

**Comment by Shannon-Dubay** [comment] 2020-05-06 17:25
Hi- sorry @PhilipFaure don't kill me but I need one more thing. Not sure how you want to go about it. Currently your 'reference images only' exporter (which I have just tested and works nicely!) exports by individuals (each individual gets their own folder). The way you have it now is how we export regular images in the "Identified Individuals" section of the exporter tools, and I think it will be very useful, so it should stay as is. 

But Reco requires all the reference images to be combined together, not by individual. At the moment that means users will have to open all the individual folders and then all the position (Right, Left, etc) folders to compile them in another combined folder. Is there maybe a way to just add an additional folder in the output, under all the individual folders, that is called "All" and includes all the reference images from all individuals together? 

![image](https://user-images.githubusercontent.com/48274721/81207962-adcab780-8fce-11ea-9e5c-d042989ec0dc.png)

Also, I foresee users wanting this feature to be available for local dtbs, as its useful for things that don't require the dtbs be on the server (such as creating a ID toolbox to send to reserve managers).

**Comment by Shannon-Dubay** [comment] 2020-05-06 17:29
ideally this "All" folder would only be created if the user specifies "All" in the "Individual" field when exporting, but not sure how much of a headache it would be do implement that.

**Comment by PhilipFaure** [comment] 2020-05-06 18:08
Thanks @Shannon-Dubay - I will look at it soon

**Comment by PhilipFaure** [comment] 2020-05-06 19:45
Hey @Shannon-Dubay 
I have fixed it on the server side, however I have not yet implemented it on local side. @RossPitman told me to only do server side, I can't remember what the reason for this is, Ross? Happy to implement on local side as well if thou be summoned by the boss!

Also, I named the folder "Gathered_Export" instead of "All" for now, as I am scared the All folder will give the illusion that all reference images are in there, however in cases where only some individuals were selected for export only those will be in this folder. Please advice on wording

![Screenshot 2020-05-06 at 21 38 01 (2)](https://user-images.githubusercontent.com/24668143/81221211-d0ff6200-8fe2-11ea-9451-d291dc5ea7b8.png)

**Comment by Shannon-Dubay** [comment] 2020-05-07 09:10
Hi Phil, this is great, thanks for the quick turn around!! 
I see your point about naming the folder "All"... I think "gathered" works. Thanks so much

**Comment by RossPitman** [comment] 2020-06-11 08:36
Can this be closed now? @PhilipFaure

**Comment by PhilipFaure** [comment] 2020-06-11 09:04
@RossPitman should I implement this on local side as well?

**Comment by RossPitman** [comment] 2020-06-17 04:11
@PhilipFaure – confirm we decided to implement this locally too? Many thanks.

**Comment by PhilipFaure** [comment] 2020-06-17 04:49
Thanks @RossPitman - confirmed, will implement these changes soon.

**Comment by PhilipFaure** [comment] 2020-06-17 15:53
Resolved. Closing issue.

**Closed by PhilipFaure** 2020-06-17 15:53 UTC
