### ISSUE TITLE
Data Processing/Manual Identification - IDS Crashes Loading Images

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#88] opened 2020-04-07 08:28 UTC
Users are not able to load more than 50ish images; IDS crashes. Note: previously when working in this module, I was able to load up to 90ish images without it crashing.

From Jo via the Forum:
On S33, S38, when filtering to any SC species (and selecting "All" for all other drop-down menu), IDS crashes when clicking "View Images". I believe it is an issue with image viewer as when loading S32, and filtering to "Cat_Leopard" ("All" for all other drop-down menu) it crashes but when filtering to "Cat_Jungle" it doesn't, the former species has 99 images while the later has 16. I also loaded S32 from admin schema and  SEAsia, still same issue.
S31 and S39 work fine (max # images = 52).

From Lauren via the Forum:
IDS crashes whenever I click 'View Primary/Secondary Images' when trying to view more than 50 images of any database, both server and local. Anything below 50 I am able to load without an issue. I am trying to load 83 'Leopard_African_Unknown_NA' images in order to manually ID the good quality images for S7_2019 from the server. I don't have an immediate solution as I cannot load just one side (Left/Right) at a time due to the images being 'unidentified'.
I have tried when the images are on an external and in ids_vol but it crashes either way. This has been happening on any PC/laptop I have used (haven't tried the Leopard PC which is at the office), both latest and beta, also running the latest version of IDS. No Log File is produced. 

See original forum post here: http://www.pantheraids.org/forum.html?p=post%2Fids-crashes-10469260%3Fpid%3D1311172725

**Comment by RossPitman** [comment] 2020-04-09 10:39
Duplicate of #89

**Closed** 2020-04-14 12:11 UTC
